GET http://localhost:3003/ping

###
GET http://localhost:3003/users

###
POST http://localhost:3003/users
Content-Type: application/json

{
    "id":"teste0140",
    "name":"teste40 rotas",
    "email":"teste0140@email",
    "password":"teste123"
}

###

GET http://localhost:3003/accounts/a003[TESTE]/balance

###
GET http://localhost:3003/accounts

###

POST http://localhost:3003/accounts
Content-Type: application/json

{
    "id":"a004[TESTE ROTAS]",
    "ownerId":"teste01"
}

###
PUT http://localhost:3003/accounts/a003[TESTE]/balance
Content-Type: application/json

{
    "value": 5
}