GET http://localhost:3003/ping

###

GET http://localhost:3003/users

###
POST http://localhost:3003/users
Content-Type: application/json

{
    "id":"teste014",
    "name":"teste4 camada business",
    "email":"teste014@email",
    "password":"teste123"
}

###

GET http://localhost:3003/accounts/a001/balance

###
GET http://localhost:3003/accounts

###

POST http://localhost:3003/accounts
Content-Type: application/json

{
    "id":"a004[TESTE camada business]",
    "ownerId":"teste01"
}

###
PUT http://localhost:3003/accounts/a003[TESTE]/balance
Content-Type: application/json

{
    "value": 50000
}